server {
    listen 80;
    server_name creative.localhost;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name creative.localhost;

    ssl_certificate /etc/nginx/certs/creative.crt;
    ssl_certificate_key /etc/nginx/certs/creative.key;

    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}