server {
    listen 80;
    server_name _;

    # Laravel
    location / {
        root /var/www/laravel/public;
        index index.php index.html;
        try_files $uri $uri/ /index.php?$query_string;

        location ~ \.php$ {
            fastcgi_pass cf_laravel:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }

    # Прокси на FastAPI
    location /api/ {
        proxy_pass http://cf_fastapi:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
